package model;

// Generated 05-mar-2015 23:16:25 by Hibernate Tools 3.4.0.CR1

/**
 * Answer generated by hbm2java
 */
public class Answer implements java.io.Serializable {

	private int idAnswer;
	private String text;
	private Boolean isCorrect;
	private Integer idQuestion;
	
	public Answer() {
		
	}

	public Answer(String text, Boolean isCorrect,
			Integer idQuestion) {
		//this.idAnswer = idAnswer;
		this.text = text;
		this.isCorrect = isCorrect;
		this.idQuestion = idQuestion;
	}
	public Answer(int idAnswer) {
		this.idAnswer = idAnswer;
	}

	

	public int getIdAnswer() {
		return this.idAnswer;
	}

	public void setIdAnswer(int idAnswer) {
		this.idAnswer = idAnswer;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public Boolean getIsCorrect() {
		return this.isCorrect;
	}

	public void setIsCorrect(Boolean isCorrect) {
		this.isCorrect = isCorrect;
	}

	public Integer getIdQuestion() {
		return this.idQuestion;
	}

	public void setIdQuestion(Integer idQuestion) {
		this.idQuestion = idQuestion;
	}

}
