package model;

// Generated 05-mar-2015 23:16:25 by Hibernate Tools 3.4.0.CR1

/**
 * Question generated by hbm2java
 */
public class Question implements java.io.Serializable {

	private int idQuestion;
	private String text;
	private String category;
	
	public Question() {
		
	}

	public Question(int idQuestion, String text, String category) {
		this.idQuestion = idQuestion;
		this.text = text;
		this.category = category;
	}
	
	public Question(int idQuestion) {
		this.idQuestion = idQuestion;
	}

	

	public int getIdQuestion() {
		return this.idQuestion;
	}

	public void setIdQuestion(int idQuestion) {
		this.idQuestion = idQuestion;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

}
